<?php

	$output = "";
	$output = "<div>";
	$output .= "<h5>Note: Select the Reusable Epics you want to add or select a group then click add to backlog button.</h5>";
	$output .= "<input id='create-scenarios-button' type='button' value='Add Reusable Epics'>";
	$output .= "<input id='create-scenarios-button' type='button' class='addtobacklog' value='Add to backlog'>";
	$output .= "<p>Select Group: <select id='filtergroup'><option></option></select></p>";
	$output .="<h4></h4>";
	$output .= "<input type='hidden' id='max_story_id' value='0' style='visibility:hidden;'>";
	$output .= "</div>";
	$output .="<table id='scenarios_stories_table' class='display table responsive dataTable no-footer dtr-inline' cellspacing='0'>";
    $output .="<thead>";
    $output .="<tr>";
    $output .="    <th >Order</th>";
    $output .="    <th >Key</th>";
    $output .="    <th style=''>Story ID</th>";
    $output .="    <th style='width: display: none;' >Sprint #<select id='selectinput' style='border:none;'></select></th>";
    $output .="    <th style=''>As a...</th>";                  
    $output .="    <th style=''>I want...</th>";
    $output .="    <th style=''>So that...</th>";
    $output .="    <th style=''>Acceptance Test</th>";
    $output .="    <th style=''>Story Points</th>";
    $output .="    <th style=''>Comments</th>";
    $output .="    <th class='dt-head-left' >Status</th>";
    $output .="    <th class='dt-head-left' style=''>Action</th>";
    $output .="</tr>";
	$output .="</thead>";
	$output .="</table>";
	$output .= "<div id='modal-body'>";
	$output .="   <div class='modal-content scenarios-modal'>";
	$output .="       <div class='modal-header'>";
	$output .="           <span id='scenarios-close' class='close'>×</span>";
	$output .="           <h2>Reusable Epics</h2>";
	$output .="       </div>";
	$output .="<div class='scenarios-field-group'>";
	$output .="       <div class='scenarios-col'>";
	$output .="			<div class='scenarios-row'>";
	$output .="		 	</div>";
	$output .="			<div class='scenarios-row'>";
	$output .="          	<h5> Note: Please select a group or add a text in the group name. </h5>";
	$output .="		 	</div>";
	$output .="       </div>";

	
	$output .="<div class='scenarios-col'>";
	$output .="			<div class='scenarios-row'>";
	$output .="          	<div class='scenarios-label'>Group: </div>";
	$output .="		 	</div>";
	$output .="			<div class='scenarios-row'>";
	$output .="<input id='scenarios-group' name='group_scenarios' type='text' class='scenarios-field' style='width: 167px;' list='scenarios-dropdown'>";
	$output .="<datalist id='scenarios-dropdown'>";
	//$output .="		    <option></option>";
	$output .="</datalist>";
	$output .="<div class='Scenario_DTE_Field_Error scenario_group'>Group... field is required</div>";
	$output .="		 	</div>";
	$output .="</div>";

	$output .="       <div class='scenarios-col'>";
	$output .="			<div class='scenarios-row'>";
	$output .="          	<div class='scenarios-label'>As a...: </div>";
	$output .="		 	</div>";
	$output .="			<div class='scenarios-row'>";
	$output .="          	<input id='scenarios-as-a' type='text' class='scenarios-field'>";
	$output .="<div class='Scenario_DTE_Field_Error scenario_as_a'>\"As a\" field is required</div>";
	$output .="		 	</div>";
	$output .="       </div>";
	$output .="       <div class='scenarios-col'>";
	$output .="			<div class='scenarios-row'>";
	$output .="          	<div class='scenarios-label'>I want...: </div>";
	$output .="		 	</div>";
	$output .="			<div class='scenarios-row'>";
	$output .="          	<input id='scenarios-i-want-to' type='text' class='scenarios-field'>";
	$output .="<div class='Scenario_DTE_Field_Error scenario_i_want'>\"I want\" field is required</div>";
	$output .="		 	</div>";
	$output .="       </div>";
	$output .="       <div class='scenarios-col'>";
	$output .="			<div class='scenarios-row'>";
	$output .="          	<div class='scenarios-label'>So that...: </div>";
	$output .="		 	</div>";
	$output .="			<div class='scenarios-row'>";
	$output .="          	<input id='scenarios-so-that' type='text' class='scenarios-field'>";
	$output .="<div class='Scenario_DTE_Field_Error scenario_so_that'>\"So that\" field is required</div>";
	$output .="		 	</div>";
	$output .="       </div>";
	$output .="       <div class='scenarios-col'>";
	$output .="			<div class='scenarios-row'>";
	$output .="          	<div class='scenarios-label'>Acceptance Test: </div>";
	$output .="		 	</div>";
	$output .="			<div class='scenarios-row'>";
	$output .="          	<Textarea type='text' class='scenarios-field' id='scenarios-acceptance-test'></Textarea>";
	$output .="<div class='Scenario_DTE_Field_Error scenario_acceptance_test'>\"Acceptance Test\" field is required</div>";
	$output .="		 	</div>";
	$output .="       </div>";
	$output .="       <div class='scenarios-col'>";
	$output .="			<div class='scenarios-row'>";
	$output .="          	<div class='scenarios-label'>Story Points: </div>";
	$output .="		 	</div>";
	$output .="			<div class='scenarios-row'>";
	$output .="<select id='scenarios-story-points'  class='recurring-field' required=''>";
	$output .="<option disabled='true' selected='' value=''> -- estimated points -- </option>";
	$output .="<option value='1'>1</option>";
	$output .="<option value='2'>2</option>";
	$output .="<option value='3'>3</option>";
	$output .="<option value='5'>5</option>";
	$output .="<option value='8'>8</option>";
	$output .="<option value='13'>13</option>";
	$output .="<option value='21'>21</option>";
	$output .="<option value='34'>34</option>";
	$output .="<option value='55'>55</option>";
	$output .="<option value='89'>89</option>";
	$output .="<option value='144'>144</option>";
	$output .="</select>";
	//$output .="          	<input id='scenarios-story-points' type='text' class='scenarios-field'>";
	$output .="<div class='Scenario_DTE_Field_Error scenario_story_points'>\"Story Points\" field is required</div>";
	$output .="		 	</div>";
	$output .="       </div>";
	$output .="       <div class='scenarios-col'>";
	$output .="			<div class='scenarios-row'>";
	$output .="          	<div class='scenarios-label'>Comments.: </div>";
	$output .="		 	</div>";
	$output .="			<div class='scenarios-row'>";
	$output .="          	<input id='scenarios-comments' type='text' class='scenarios-field'>";
	$output .="		 	</div>";
	$output .="       </div>";
	$output .="</div>";
	$output .="       <div class='modal-footer scenarios-footer'>";
	$output .="           <div class=''>";
	$output .="               <button id='save-scenarios' class='scenarios-save'>Save</button>";
	$output .="           </div>";
	$output .="       </div>";
	$output .="   </div>";
	$output .="</div>";


	

	$output .="<div id='scenarios-modal-body' >";
	$output .="<div class='modal-content delete-scenarios-modal' style='width: 45% !important;'>";
	$output .="       <div class='modal-header'>";
	$output .="           <h2 >Confirm Delete</h2>";
	$output .="       </div>";
	$output .="		  <div class='scenarios-content'>";
	$output .="		  <h4>Are you sure you want to delete this Scenario?</h4>";
	$output .="		  </div>";
	$output .="<div class='modal-footer scenarios-footer'>";
	$output .="    <div class='confirm-delete-scenarios'>";
	$output .="    	  <button id='delete-scenarios' class='scenarios-delete'>Yes</button>";
	$output .="    	  <button id='cancel-delete-scenarios' onclick='close_delete_scenarios_modal()' class='scenarios-cancel'>Cancel</button>";				  
	$output .="    </div>";
	$output .="</div>";
	$output .="<input type='hidden' id='scenarios_is_edit' value=''>";
	$output .="<input type='hidden' id='scenarios_edit_key' value=''>";
	$output .="   </div>";


	echo $output;
?>